/*
 * Production-ready Express server for the DigitalBank MVP. This server is
 * designed for a production environment:
 *
 *  - Persistent storage using Firestore
 *  - Basic endpoints for savings, device, and reset
 *  - CORS enabled for web frontend access
 *  - Security best practices via Helmet
 *
 * Author: Generated by ChatGPT on behalf of the DigitalBank project.
 */

const express = require('express');
const helmet = require('helmet');
const morgan = require('morgan');
const admin = require('firebase-admin');

// Load environment variables. In production, set these via your
// hosting provider or a .env file (using the `dotenv` package).
const PORT = process.env.PORT || 3000;

// Initialise the Firebase Admin SDK. When running on a GCP
// environment (e.g. Cloud Run), credentials can be provided by
// the environment. Locally, ensure you have a service account JSON
// file and set GOOGLE_APPLICATION_CREDENTIALS.
try {
    admin.initializeApp({
        credential: admin.credential.applicationDefault(),
    });
} catch (err) {
    console.error('Firebase Admin initialization error:', err);
}

const db = admin.firestore();

// Firestore collection/document constants.
const COLLECTION_NAME = 'digitalbank';
const DOC_NAME = 'savings';

const app = express();

/**
 * Helmet:
 * - CSPは維持
 * - ただし public/web.html のような「インライン <script>」を動かすために
 *   script-src に 'unsafe-inline' を追加
 *
 * これにより “JSが一切動かない” 症状（iPhone Safariで顕著）が解消されます。
 * ※より安全にするには nonce/sha256 方式にして unsafe-inline を無くすのが理想です。
 */
app.use(
    helmet({
        contentSecurityPolicy: {
            useDefaults: true,
            directives: {
                // デフォルトの script-src だとインライン <script> がブロックされるため許可
                'script-src': ["'self'", "'unsafe-inline'"],
                'script-src-attr': ["'self'", "'unsafe-inline'"],
            },
        },
    })
);

app.use(morgan('combined'));
app.use(express.json());

// Serve static files from the `public` directory so that the web frontend
// (e.g. web.html) can be hosted by the same server. This helps avoid
// CORS issues because the frontend and API share the same origin. Place
// your web assets (HTML, CSS, JS) under a folder named `public` next
// to this server.js file.
app.use(express.static('public'));

// CORS: Allow requests from any origin. In a real production app,
// restrict this to your known domain(s).
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'OPTIONS') {
        return res.sendStatus(204);
    }
    next();
});

/**
 * GET /api/device
 *
 * Returns the current total savings. The deviceId query parameter can
 * be used if you want separate totals per device, but for this MVP we
 * store a single total.
 */
app.get('/api/device', async (req, res) => {
    try {
        const docRef = db.collection(COLLECTION_NAME).doc(DOC_NAME);
        const snapshot = await docRef.get();
        const data = snapshot.exists ? snapshot.data() : { total: 0 };
        res.json({ total: data.total || 0 });
    } catch (err) {
        console.error('/api/device error:', err);
        res.status(500).json({ error: 'Failed to fetch device total' });
    }
});

/**
 * POST /api/savings
 *
 * Body: { amount: number, deviceId?: string }
 * Adds the amount to the total and returns the updated total.
 */
app.post('/api/savings', async (req, res) => {
    try {
        const amount = Number(req.body.amount);
        if (!Number.isFinite(amount) || amount <= 0) {
            return res.status(400).json({ error: 'Invalid amount' });
        }

        const docRef = db.collection(COLLECTION_NAME).doc(DOC_NAME);

        const result = await db.runTransaction(async (t) => {
            const snap = await t.get(docRef);
            const current = snap.exists && snap.data().total ? Number(snap.data().total) : 0;
            const updated = current + amount;
            t.set(docRef, { total: updated }, { merge: true });
            return updated;
        });

        res.json({ total: result });
    } catch (err) {
        console.error('/api/savings error:', err);
        res.status(500).json({ error: 'Failed to add savings' });
    }
});

/**
 * POST /api/reset
 *
 * Resets the total savings back to 0.
 */
app.post('/api/reset', async (req, res) => {
    try {
        const docRef = db.collection(COLLECTION_NAME).doc(DOC_NAME);
        await docRef.set({ total: 0 }, { merge: true });
        res.json({ total: 0 });
    } catch (err) {
        console.error('/api/reset error:', err);
        res.status(500).json({ error: 'Failed to reset savings' });
    }
});

// Health check endpoint
app.get('/health', (req, res) => res.status(200).send('OK'));

app.listen(PORT, () => {
    console.log(`DigitalBank server running on port ${PORT}`);
});
